/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 单个物理 MDD 二进制资源入口。 */
export declare class Mdd {
  /** 打开一份物理 MDD 文件。 */
  static open(path: string, options?: OpenOptions | undefined | null): Mdd
  /** 返回该 MDD 文件的元数据。 */
  get metadata(): DictionaryMetadata
  /** 创建该文件的 key 批量扫描器。 */
  keys(): MddKeyScanner
  /** 创建该文件的 key+record 批量扫描器。 */
  entries(): MddEntryScanner
  /** 查找一个资源 key，并返回该文件内的 record 地址。 */
  findKey(word: string): Promise<DictionaryEntry | null>
  /** 返回该文件中全部精确匹配的资源位置。 */
  findKeys(word: string): Promise<DictionaryEntry[]>
  /** 异步返回该文件中以指定前缀开头的资源 key。 */
  prefix(prefix: string): Promise<DictionaryEntry[]>
  /** 读取该文件中的一个原始 record。 */
  readRecord(start: bigint, end: bigint): Promise<Buffer>
  /** 查找并读取一个 MDD 二进制资源。 */
  lookup(word: string): Promise<MddResource | null>
  /** Deterministically release the MDD memory mapping when it is no longer busy. */
  close(): boolean
}

/** 单个 MDD 文件的 entry 批量扫描器。 */
export declare class MddEntryScanner {
  /** 读取下一批单文件 MDD key 与原始资源 bytes。 */
  nextBatch(batchSize?: number | undefined | null): Promise<EntryBatch>
}

/** 单个 MDD 文件的 key 批量扫描器。 */
export declare class MddKeyScanner {
  /** 读取下一批单文件 MDD key。 */
  nextBatch(batchSize?: number | undefined | null): Promise<KeyBatch>
}

/** 按调用方顺序查询多个物理 MDD 文件的资源列表入口。 */
export declare class MddList {
  /** 按调用方提供的路径顺序打开 MDD 文件列表。 */
  static open(paths: Array<string>, options?: OpenOptions | undefined | null): MddList
  /** 返回列表包含的物理 MDD 文件数量。 */
  get volumeCount(): number
  /** 创建跨全部文件的 key 批量扫描器。 */
  keys(): MddListKeyScanner
  /** 创建跨全部文件的 key+record 批量扫描器。 */
  entries(): MddListEntryScanner
  /** 查找一个资源 key，并返回所在文件和 record 地址。 */
  findKey(word: string): Promise<MddListDictionaryEntry | null>
  /** 返回列表中全部精确匹配的资源位置。 */
  findKeys(word: string): Promise<MddListDictionaryEntry[]>
  /** 返回全部文件中以指定前缀开头的资源 key。 */
  prefix(prefix: string): Promise<MddListDictionaryEntry[]>
  /** 读取指定文件中的一个原始 record。 */
  readRecord(volume: number, start: bigint, end: bigint): Promise<Buffer>
  /** 按文件优先级查找并读取一个 MDD 二进制资源。 */
  lookup(word: string): Promise<MddResource | null>
  /** Deterministically release every MDD volume mapping when no operation is busy. */
  close(): boolean
}

/** MDD 文件列表的 entry 批量扫描器。 */
export declare class MddListEntryScanner {
  /** 读取下一批跨文件 MDD key 与原始资源 bytes。 */
  nextBatch(batchSize?: number | undefined | null): Promise<EntryBatch>
}

/** MDD 文件列表的 key 批量扫描器。 */
export declare class MddListKeyScanner {
  /** 读取下一批跨文件 MDD key。 */
  nextBatch(batchSize?: number | undefined | null): Promise<MddListKeyBatch>
}

/** 文本词典入口。除基础二进制读取外，还负责 LINK 和 StyleSheet 语义。 */
export declare class Mdx {
  /** 打开一份 MDX 文件。 */
  static open(path: string, options?: OpenOptions | undefined | null): Mdx
  /** 返回词典元数据。 */
  get metadata(): DictionaryMetadata
  /** 创建顺序 key 批量扫描器。 */
  keys(): MdxKeyScanner
  /** 创建顺序 key+record 批量扫描器。 */
  entries(): MdxEntryScanner
  /** 读取一个可能跨越多个 Record Block 的原始 record。 */
  readRecord(start: bigint, end: bigint): Promise<Buffer>
  /** 读取并解码 MDX record，可选展开 LINK 链和 StyleSheet。 */
  readRecordText(start: bigint, end: bigint, redirectLink: boolean): Promise<string>
  /** 异步查找一个精确 key。 */
  findKey(word: string): Promise<DictionaryEntry | null>
  /** 异步查找全部精确匹配 key，按 MDX 原始顺序返回。 */
  findKeys(word: string): Promise<DictionaryEntry[]>
  /** 异步返回 comparison key 以指定前缀开头的全部 MDX key。 */
  prefix(prefix: string): Promise<DictionaryEntry[]>
  /** 查找 key 并返回解析后的 UTF-8 文本。 */
  lookupText(word: string): Promise<string | null>
  /** 查找全部精确匹配 key 并返回解析后的 UTF-8 文本。 */
  lookupAllText(word: string): Promise<string[]>
  /** Deterministically release the MDX memory mapping when it is no longer busy. */
  close(): boolean
}

/** MDX entry 批量扫描器。 */
export declare class MdxEntryScanner {
  /** 读取下一批 MDX key 与原始 record bytes。 */
  nextBatch(batchSize?: number | undefined | null): Promise<EntryBatch>
}

/** MDX key 批量扫描器。 */
export declare class MdxKeyScanner {
  /** 读取下一批 MDX key。 */
  nextBatch(batchSize?: number | undefined | null): Promise<KeyBatch>
}

/** 一个 MDX key 以及其 record 地址范围。 */
export interface DictionaryEntry {
  keyText: string
  recordStart: bigint
  recordEnd: bigint
}

/** Node-API 暴露的稳定元数据视图。 */
export interface DictionaryMetadata {
  path: string
  kind: string
  version: string
  engineVersion: number
  requiredVersion?: number
  encoding: string
  encrypted: number
  title: string
  description: string
  format: string
  keyCaseSensitive: boolean
  stripKey: boolean
  attributes: Record<string, string>
  warnings: Array<string>
  rawHeaderXml: string
  entryCount: bigint
  keyBlockCount: bigint
  recordBlockCount: bigint
  totalDecompressedRecordSize: bigint
  mappedFileSize: bigint
}

/** 一条带原始 record bytes 的 entry。 */
export interface DictionaryRawEntry {
  keyText: string
  data: Buffer
}

/** 一批带原始 record bytes 的 entry。 */
export interface EntryBatch {
  entries: Array<DictionaryRawEntry>
  done: boolean
}

/** 一批 key 扫描结果。 */
export interface KeyBatch {
  entries: Array<DictionaryEntry>
  done: boolean
}

/** 一个 MDD 列表 key 以及所在文件和 record 地址范围。 */
export interface MddListDictionaryEntry {
  keyText: string
  volume: number
  recordStart: bigint
  recordEnd: bigint
}

/** 一批 MDD 列表 key 扫描结果。 */
export interface MddListKeyBatch {
  entries: Array<MddListDictionaryEntry>
  done: boolean
}

/** MDD 的二进制 lookup 结果。 */
export interface MddResource {
  keyText: string
  data: Buffer
}

/** Node-API 打开选项。 */
export interface OpenOptions {
  maximumHeaderSizeBytes?: number
  maximumIndexCompressedSizeBytes?: number
  maximumIndexDecompressedSizeBytes?: number
  maximumBlockCompressedSizeBytes?: number
  maximumBlockDecompressedSizeBytes?: number
  maximumKeyTextSizeBytes?: number
  maximumRecordSizeBytes?: number
  maximumBlockCount?: number
  maximumMddVolumeCount?: number
  keyBlocksCacheBytes?: number
  recordBlocksCacheBytes?: number
  userId?: string
  regCode?: string
  keyFile?: string
}
