/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MdictDictionary {
  static open(path: string, options?: OpenOptions | undefined | null): MdictDictionary
  get metadata(): DictionaryMetadata
  createScanner(): MdictEntryScanner
  readRecord(start: bigint, end: bigint): Promise<Buffer>
  lookupKeyBlockByWord(word: string): Promise<DictionaryEntry | null>
  lookup(word: string): Promise<DictionaryLookup>
}

export declare class MdictEntryScanner {
  nextBatch(batchSize?: number | undefined | null): Promise<EntryBatch>
}

export interface DictionaryEntry {
  keyText: string
  keyBlock: number
  recordStart: bigint
  recordEnd: bigint
  firstRecordBlock: number
}

export interface DictionaryLookup {
  keyText: string
  definition: string | null
}

export interface DictionaryMetadata {
  path: string
  kind: string
  engineVersion: number
  requiredVersion?: number
  encoding: string
  encrypted: number
  title: string
  description: string
  format: string
  keyCaseSensitive: boolean
  stripKey: boolean
  attributes: Record<string, string>
  warnings: Array<string>
  rawHeaderXml: string
  entryCount: bigint
  keyBlockCount: bigint
  recordBlockCount: bigint
  totalDecompressedRecordSize: bigint
}

export interface EntryBatch {
  entries: Array<DictionaryEntry>
  done: boolean
}

export interface OpenOptions {
  maximumHeaderSizeBytes?: number
  maximumIndexCompressedSizeBytes?: number
  maximumIndexDecompressedSizeBytes?: number
  maximumBlockCompressedSizeBytes?: number
  maximumBlockDecompressedSizeBytes?: number
  maximumKeyTextSizeBytes?: number
  maximumRecordSizeBytes?: number
  maximumBlockCount?: number
}
