export const SEARCH_POPOVER_SUGGESTION_LIMIT = 30
export const SEARCH_POPOVER_MAX_VISIBLE_ROWS = 10
export const SEARCH_POPOVER_ROW_HEIGHT = 42
export const SEARCH_POPOVER_SUGGESTION_LIST_MAX_HEIGHT =
  SEARCH_POPOVER_MAX_VISIBLE_ROWS * SEARCH_POPOVER_ROW_HEIGHT
